version: '3'

vars:
  APP_NAME: committed
  BUILD_DIR: .build
  COV_DIR: .coverage

tasks:
  prepare:
    desc: one-time post-clone repo setup
    cmds:
      - go mod tidy
      - 'echo "NYI: bootstrapping committed as the commit-msg hook?"'

  run:
    desc: run from code
    cmds:
      - go run ./... {{.CLI_ARGS}}

  example:
    desc: run example case (dummy test file)
    aliases: [ ex ]
    cmds:
      - 'printf "chore: dummy message\n\nYou can edit this.\n" > MSG'
      - task: run
        vars: { CLI_ARGS: MSG message }
      - cat MSG
      - rm MSG

  test:
    desc: run all tests, create coverage
    vars:
      # COV_DIR: .coverage
      COV_FILE: '{{.COV_DIR}}/coverage.out'
    cmds:
      - mkdir -p {{.COV_DIR}}
      - go test ./... -coverprofile={{.COV_FILE}}
      - go tool cover -html={{.COV_FILE}} -o {{.COV_DIR}}/coverage.html
      - go tool gcov2lcov -infile {{.COV_FILE}} -outfile {{.COV_DIR}}/lcov.info

  test:watch:
    desc: test in watch mode
    watch: true
    sources: [ '**/*.go' ]
    cmds:
      - task: test

  test:show:
    desc: show test coverage
    deps:
      - test
    cmds:
      - xdg-open {{.COV_DIR}}/coverage.html

  clean:
    desc: clean all generated files
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -rf {{.COV_DIR}}

  build:
    desc: build the binary to '{{.BUILD_DIR}}/{{.APP_NAME}}'
    cmds:
      - mkdir -p '{{.BUILD_DIR}}'
      - go build -o '{{.BUILD_DIR}}/{{.APP_NAME}}' .

  install:
    desc: install from '{{.BUILD_DIR}}/{{.APP_NAME}}'
    vars:
      GOPATH:
        sh: go env GOPATH
    deps:
      - build
    cmds:
      # should this use `go install` instead?
      - cp '{{.BUILD_DIR}}/{{.APP_NAME}}' '{{.GOPATH}}/bin/{{.APP_NAME}}'

  lint:
    desc: run go vet and go test as a lightweight lint step
    cmds:
      - go vet ./...
      - go test ./...

  release:test:
    desc: test the release process
    deps:
      - lint
      - build
    env:
      VER_CUR:
        sh: go tool svu current
      VER_NEXT:
        sh: go tool svu next
    cmds:
      - echo "svu says ${VER_CUR} -> ${VER_NEXT}"
      - go tool goreleaser release --clean --snapshot --skip=publish --skip=sign --skip=sbom {{.CLI_ARGS}}
