name: CI

on:
  push:
    branches: [ main ]
  pull_request: {}
  workflow_dispatch: {} # manual trigger for testing

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - uses: go-task/setup-task@v2

      - run: task lint

      - run: task test

      - run: task build

      - run: task release:test

  release:
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - uses: go-task/setup-task@v2

      - run: task tag-release

      - run: task release
