name: release

# disable for now...
on: {}
  # push:
  #   branches: []
  #   tags: [ v* ]

jobs:
  release:
    permissions:
      attestations: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - uses: go-task/setup-task@v2

      - run: task release
