name: release

on:
  push:
    branches: []
    tags: [ v* ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - uses: go-task/setup-task@v2

      - run: task release
